OpenGL Ray/Path Tracing: src/scene/bvh.cpp File Reference
bvh.cpp File Reference
#include <glm/gtc/matrix_transform.hpp>
#include "scene/model.h"
#include "scene/bvh.h"
#include <algorithm>
#include <vector>
#include <memory>
Classes
struct BuildRef
Functions
static glm::vec3 tri_min (const CPU_Triangle &t)
static glm::vec3 tri_max (const CPU_Triangle &t)
static glm::vec3 tri_centroid (const CPU_Triangle &t)
static int build_recursive (std::vector< BVHNode > &nodes, const std::vector< CPU_Triangle > &tris, std::vector< BuildRef > &refs, const int begin, const int end, const int leafMax=8)
std::vector< BVHNode > build_bvh (std::vector< CPU_Triangle > &tris)
Builds a simple median-split BVH from CPU triangles.
void upload_bvh_tbo (const std::vector< BVHNode > &nodes, const std::vector< CPU_Triangle > &tris, GLuint &outNodeTex, GLuint &outNodeBuf, GLuint &outTriTex, GLuint &outTriBuf)
Uploads BVH nodes and triangles to GPU texture buffers (TBOs).
void gather_model_triangles (const Model &model, const glm::mat4 &M, std::vector< CPU_Triangle > &outTris)
Extracts triangles from a Model into CPU triangle format.
bool rebuild_bvh_from_model_path (const char *path, const glm::mat4 &modelTransform, std::unique_ptr< Model > &bvhModel, int &outNodeCount, int &outTriCount, BVHHandle &handle)
High-level helper for loading a model and building its BVH.
Function Documentation
build_bvh()
std::vector< BVHNode > build_bvh (std::vector< CPU_Triangle > & tris)
Builds a simple median-split BVH from CPU triangles.
The resulting BVH uses a binary tree with splitting based on the longest axis of the node bounding box, partitioned by median position.
Parameters
tris Input/output triangle list. Order may be modified.
Returns
Linear array of BVHNode, representing the flattened tree.
Definition at line 94 of file bvh.cpp.
References build_recursive(), and tri_centroid().
Referenced by rebuild_bvh_from_model_path().
build_recursive()
int build_recursive (std::vector< BVHNode > & nodes, const std::vector< CPU_Triangle > & tris, std::vector< BuildRef > & refs, const int begin, const int end, const int leafMax = 8) static
Definition at line 41 of file bvh.cpp.
References build_recursive(), tri_max(), and tri_min().
Referenced by build_bvh(), and build_recursive().
gather_model_triangles()
void gather_model_triangles (const Model & model, const glm::mat4 & M, std::vector< CPU_Triangle > & outTris)
Extracts triangles from a Model into CPU triangle format.
The function reads vertex/index buffers from a LearnOpenGL-style Model class, converts triangles into CPU_Triangle format, and applies a model transformation matrix to the vertex positions.
Parameters
model Source Model containing positions and indices.
M Transform to apply to all triangle vertices.
outTris Output vector of CPU_Triangle structures.
Definition at line 225 of file bvh.cpp.
References CPU_Triangle::e1, CPU_Triangle::e2, Model::meshes, and CPU_Triangle::v0.
Referenced by rebuild_bvh_from_model_path().
rebuild_bvh_from_model_path()
bool rebuild_bvh_from_model_path (const char * path, const glm::mat4 & modelTransform, std::unique_ptr< Model > & bvhModel, int & outNodeCount, int & outTriCount, BVHHandle & handle)
High-level helper for loading a model and building its BVH.
Loads a model from disk, extracts triangles, builds a BVH, and uploads the resulting nodes and triangle data into GPU buffers/TBOs.
Old BVH data and the previous model (if any) are deleted and replaced.
Parameters
path File path to the model to load.
modelTransform Transform applied to the model geometry.
bvhModel Output unique_ptr containing the loaded model.
outNodeCount Output number of BVH nodes.
outTriCount Output number of triangles.
handle Output BVHHandle whose textures/buffers will be filled.
Returns
True on success, false if the model failed to load.
Definition at line 249 of file bvh.cpp.
References build_bvh(), gather_model_triangles(), BVHHandle::nodeBuf, BVHHandle::nodeTex, BVHHandle::release(), BVHHandle::triBuf, BVHHandle::triTex, and upload_bvh_tbo().
tri_centroid()
glm::vec3 tri_centroid (const CPU_Triangle & t) static
Definition at line 22 of file bvh.cpp.
References CPU_Triangle::e1, CPU_Triangle::e2, and CPU_Triangle::v0.
Referenced by build_bvh().
tri_max()
glm::vec3 tri_max (const CPU_Triangle & t) static
Definition at line 16 of file bvh.cpp.
References CPU_Triangle::e1, CPU_Triangle::e2, and CPU_Triangle::v0.
Referenced by build_recursive().
tri_min()
glm::vec3 tri_min (const CPU_Triangle & t) static
Definition at line 10 of file bvh.cpp.
References CPU_Triangle::e1, CPU_Triangle::e2, and CPU_Triangle::v0.
Referenced by build_recursive().
upload_bvh_tbo()
void upload_bvh_tbo (const std::vector< BVHNode > & nodes, const std::vector< CPU_Triangle > & tris, GLuint & outNodeTex, GLuint & outNodeBuf, GLuint & outTriTex, GLuint & outTriBuf)
Uploads BVH nodes and triangles to GPU texture buffers (TBOs).
Two pairs of objects are created:
outNodeBuf + outNodeTex
outTriBuf + outTriTex
This design allows shutting down cleanly by deleting buffers while the TBO textures reference them indirectly.
Parameters
nodes Flattened BVH node array.
tris Triangle list associated with the BVH.
outNodeTex Output: texture buffer containing nodes.
outNodeBuf Output: buffer for node data.
outTriTex Output: texture buffer containing triangles.
outTriBuf Output: buffer for triangle data.
Definition at line 141 of file bvh.cpp.
Referenced by rebuild_bvh_from_model_path().