OpenGL Ray/Path Tracing: rt::Accum Class Reference
rt::Accum Class Reference
Manages the temporal accumulation buffer used by the path tracer.
#include <accum.h>
Public Member Functions
Accum ()=default
Default constructor (creates an empty, uninitialized accumulator).
~Accum ()=default
Destructor does not auto-release; release() must be called explicitly.
Accum (const Accum &)=delete
Non-copyable to avoid double-free of GL objects.
Accum & operator= (const Accum &)=delete
Accum (Accum &&other) noexcept
Move constructor — transfers ownership of GL resources.
Accum & operator= (Accum &&other) noexcept
Move assignment — transfers ownership and invalidates the source.
void reset ()
Resets the accumulated frame count.
void recreate (int w, int h)
Creates or recreates all accumulation textures.
void bindWriteFBO () const
Binds the accumulation FBO with only COLOR0 active.
void bindWriteFBO_ColorAndMotion () const
Binds the FBO to write both accumulation color and motion vectors.
void bindWriteFBO_MRT (GLuint posTex, GLuint nrmTex) const
Binds FBO with 4 MRT targets for combined RT + GBuffer output.
void clear () const
Clears the active write buffers to zero.
void swapAfterFrame ()
Advances the accumulation frame and flips the ping-pong index.
GLuint readTex () const
GLuint writeTex () const
void release ()
Releases all GPU-side resources owned by the accumulator.
Public Attributes
GLuint fbo = 0
Accumulation FBO handle.
GLuint tex [2] = {0, 0}
Ping-pong accumulation textures (RGBA16F).
GLuint motionTex = 0
Motion vector texture (RG16F), storing NDC delta per pixel.
int writeIdx = 0
Index of the accumulation texture being written to this frame.
int frameIndex = 0
Number of frames accumulated so far.
int width = 0
Current dimensions of the accumulation buffers.
int height = 0
Detailed Description
Manages the temporal accumulation buffer used by the path tracer.
This class encapsulates all GPU resources required for progressive accumulation (ping-pong textures), motion-vector storage, and MRT output. It handles creation, resizing, clearing, and binding of the underlying framebuffer object.
The accumulation buffer stores:
linear HDR color (RGBA16F)
screen-space motion vectors (RG16F)
The ping-pong scheme alternates between two color textures each frame. One texture is written to (current frame), while the other is sampled from (previous accumulated result). The class keeps track of both the active index and the current accumulation frame count.
Definition at line 24 of file accum.h.
Constructor & Destructor Documentation
Accum() [1/3]
rt::Accum::Accum () default
Default constructor (creates an empty, uninitialized accumulator).
Referenced by Accum(), Accum(), operator=(), and operator=().
~Accum()
rt::Accum::~Accum () default
Destructor does not auto-release; release() must be called explicitly.
Accum() [2/3]
rt::Accum::Accum (const Accum &) delete
Non-copyable to avoid double-free of GL objects.
References Accum().
Accum() [3/3]
rt::Accum::Accum (Accum && other) noexcept
Move constructor — transfers ownership of GL resources.
Definition at line 59 of file accum.cpp.
References Accum().
Member Function Documentation
bindWriteFBO()
void rt::Accum::bindWriteFBO () const
Binds the accumulation FBO with only COLOR0 active.
COLOR0 is set to the current write texture. Useful for simple accumulation without motion vectors.
Definition at line 160 of file accum.cpp.
References fbo, and writeTex().
bindWriteFBO_ColorAndMotion()
void rt::Accum::bindWriteFBO_ColorAndMotion () const
Binds the FBO to write both accumulation color and motion vectors.
COLOR0 → accumulation (RGBA16F)
COLOR1 → motion vectors (RG16F)
Definition at line 175 of file accum.cpp.
References fbo, motionTex, and writeTex().
Referenced by recreate().
bindWriteFBO_MRT()
void rt::Accum::bindWriteFBO_MRT (GLuint posTex, GLuint nrmTex) const
Binds FBO with 4 MRT targets for combined RT + GBuffer output.
COLOR0 → accumulation write (RGBA16F)
COLOR1 → motion (RG16F)
COLOR2 → world-space position (posTex)
COLOR3 → world-space normal (nrmTex)
Parameters
posTex World-space position buffer texture.
nrmTex World-space normal buffer texture.
Definition at line 194 of file accum.cpp.
References fbo, motionTex, and writeTex().
Referenced by renderRay().
clear()
void rt::Accum::clear () const
Clears the active write buffers to zero.
This clears both COLOR0 and COLOR1. Useful when switching modes or after resetting accumulation.
Definition at line 218 of file accum.cpp.
References fbo, motionTex, and writeTex().
Referenced by reset().
operator=() [1/2]
Accum & rt::Accum::operator= (Accum && other) noexcept
Move assignment — transfers ownership and invalidates the source.
Definition at line 64 of file accum.cpp.
References Accum(), fbo, frameIndex, height, motionTex, release(), tex, width, and writeIdx.
operator=() [2/2]
Accum & rt::Accum::operator= (const Accum &) delete
References Accum().
readTex()
GLuint rt::Accum::readTex () const inline nodiscard
Returns
The texture containing the previous frame's accumulated result.
Definition at line 133 of file accum.h.
References tex, and writeIdx.
Referenced by renderRay().
recreate()
void rt::Accum::recreate (int w, int h)
Creates or recreates all accumulation textures.
Called on window resize or initial startup. This function allocates:
two RGBA16F accumulation textures
one RG16F motion vector texture and attaches them to the FBO. Previous resources are deleted.
Parameters
w New width of render targets.
h New height of render targets.
Definition at line 106 of file accum.cpp.
References bindWriteFBO_ColorAndMotion(), fbo, frameIndex, height, motionTex, reset(), swapAfterFrame(), tex, width, and writeIdx.
release()
void rt::Accum::release ()
Releases all GPU-side resources owned by the accumulator.
Deletes FBO, ping-pong textures, and motion texture. After calling this, the object returns to an uninitialized state.
Definition at line 36 of file accum.cpp.
References fbo, frameIndex, height, motionTex, tex, width, and writeIdx.
Referenced by operator=().
reset()
void rt::Accum::reset ()
Resets the accumulated frame count.
This should be called when camera movement or parameter changes invalidate the temporal history (e.g., exposure change, SPP change). The textures themselves are not recreated; only the counters reset.
Definition at line 98 of file accum.cpp.
References clear(), frameIndex, and writeIdx.
Referenced by recreate().
swapAfterFrame()
void rt::Accum::swapAfterFrame () inline
Advances the accumulation frame and flips the ping-pong index.
Should be called once per rendered frame after the present pass.
Definition at line 125 of file accum.h.
References frameIndex, and writeIdx.
Referenced by recreate(), and renderRay().
writeTex()
GLuint rt::Accum::writeTex () const inline nodiscard
Returns
The texture being written into this frame.
Definition at line 138 of file accum.h.
References tex, and writeIdx.
Referenced by bindWriteFBO(), bindWriteFBO_ColorAndMotion(), bindWriteFBO_MRT(), clear(), and renderRay().
Member Data Documentation
fbo
GLuint rt::Accum::fbo = 0
Accumulation FBO handle.
Definition at line 27 of file accum.h.
Referenced by bindWriteFBO(), bindWriteFBO_ColorAndMotion(), bindWriteFBO_MRT(), clear(), operator=(), recreate(), and release().
frameIndex
int rt::Accum::frameIndex = 0
Number of frames accumulated so far.
Definition at line 39 of file accum.h.
Referenced by operator=(), recreate(), release(), renderRay(), reset(), and swapAfterFrame().
height
int rt::Accum::height = 0
Definition at line 42 of file accum.h.
Referenced by operator=(), recreate(), and release().
motionTex
GLuint rt::Accum::motionTex = 0
Motion vector texture (RG16F), storing NDC delta per pixel.
Definition at line 33 of file accum.h.
Referenced by bindWriteFBO_ColorAndMotion(), bindWriteFBO_MRT(), clear(), operator=(), recreate(), release(), and renderRay().
tex
GLuint rt::Accum::tex[2] = {0, 0}
Ping-pong accumulation textures (RGBA16F).
Definition at line 30 of file accum.h.
Referenced by operator=(), readTex(), recreate(), release(), and writeTex().
width
int rt::Accum::width = 0
Current dimensions of the accumulation buffers.
Definition at line 42 of file accum.h.
Referenced by operator=(), recreate(), and release().
writeIdx
int rt::Accum::writeIdx = 0
Index of the accumulation texture being written to this frame.
Definition at line 36 of file accum.h.
Referenced by operator=(), readTex(), recreate(), release(), reset(), swapAfterFrame(), and writeTex().
The documentation for this class was generated from the following files:
include/render/accum.h
src/render/accum.cpp