OpenGL Ray/Path Tracing: Shader Class Reference
Shader Class Reference
Minimal RAII wrapper for an OpenGL shader program.
#include <Shader.h>
Public Member Functions
Shader (const Shader &)=delete
Deleted copy constructor to prevent accidental copying.
Shader & operator= (const Shader &)=delete
Deleted copy assignment.
Shader (Shader &&) noexcept
Move constructor — transfers program ownership.
Shader & operator= (Shader &&) noexcept
Move assignment — releases current program and adopts another.
Shader (const char *vertexPath, const char *fragmentPath)
Constructs and links a GLSL program from two file paths.
~Shader ()
Destructor releases the GL program if valid.
void use () const
Binds the shader program for subsequent draw calls.
bool isValid () const
void setBool (const std::string &name, bool value) const
Sets a boolean uniform.
void setInt (const std::string &name, int value) const
Sets an integer uniform.
void setFloat (const std::string &name, float value) const
Sets a float uniform.
void setMat4 (const std::string &name, const glm::mat4 &mat) const
Sets a mat4 uniform (typically view/projection matrices).
void setVec3 (const std::string &name, const glm::vec3 &value) const
Sets a vec3 uniform.
void setVec2 (const std::string &name, const glm::vec2 &value) const
Sets a vec2 uniform.
Public Attributes
unsigned int ID = 0
OpenGL program object ID.
bool valid = false
Whether the shader compiled and linked successfully.
Detailed Description
Minimal RAII wrapper for an OpenGL shader program.
This class handles compilation, linking, binding, and uniform management for GLSL vertex/fragment programs. It is intentionally lightweight but provides convenience helpers for setting common uniform types.
The class is:
non-copyable (avoids double deletion of GL programs)
movable (safe transfer of ownership)
The constructor takes file paths and builds a complete shader program.
Definition at line 21 of file Shader.h.
Constructor & Destructor Documentation
Shader() [1/3]
Shader::Shader (const Shader &) delete
Deleted copy constructor to prevent accidental copying.
References Shader().
Referenced by operator=(), operator=(), Shader(), and Shader().
Shader() [2/3]
Shader::Shader (Shader && o) noexcept
Move constructor — transfers program ownership.
After the move, the source object is left in a safe, invalid state.
Definition at line 85 of file Shader.cpp.
References Shader().
Shader() [3/3]
Shader::Shader (const char * vertexPath, const char * fragmentPath)
Constructs and links a GLSL program from two file paths.
Parameters
vertexPath Path to the vertex shader file.
fragmentPath Path to the fragment shader file.
The constructor loads, compiles, links, and validates the program.
Definition at line 106 of file Shader.cpp.
References shader_detail::getDirectory(), ID, shader_detail::preprocessShaderSource(), and valid.
~Shader()
Shader::~Shader ()
Destructor releases the GL program if valid.
Definition at line 161 of file Shader.cpp.
References ID.
Member Function Documentation
isValid()
bool Shader::isValid () const inline nodiscard
Returns
True if the shader successfully compiled and linked.
Definition at line 74 of file Shader.h.
References isValid(), and valid.
Referenced by isValid().
operator=() [1/2]
Shader & Shader::operator= (const Shader &) delete
Deleted copy assignment.
References Shader(), and use().
operator=() [2/2]
Shader & Shader::operator= (Shader && o) noexcept
Move assignment — releases current program and adopts another.
Definition at line 90 of file Shader.cpp.
References ID, and Shader().
setBool()
void Shader::setBool (const std::string & name, bool value) const
Sets a boolean uniform.
Parameters
name Uniform name as in the GLSL source.
value Boolean value to upload.
Definition at line 178 of file Shader.cpp.
setFloat()
void Shader::setFloat (const std::string & name, float value) const
Sets a float uniform.
Definition at line 186 of file Shader.cpp.
Referenced by renderRay().
setInt()
void Shader::setInt (const std::string & name, int value) const
Sets an integer uniform.
Definition at line 182 of file Shader.cpp.
Referenced by renderRay().
setMat4()
void Shader::setMat4 (const std::string & name, const glm::mat4 & mat) const
Sets a mat4 uniform (typically view/projection matrices).
Definition at line 190 of file Shader.cpp.
Referenced by renderRaster().
setVec2()
void Shader::setVec2 (const std::string & name, const glm::vec2 & value) const
Sets a vec2 uniform.
Definition at line 198 of file Shader.cpp.
Referenced by renderRay().
setVec3()
void Shader::setVec3 (const std::string & name, const glm::vec3 & value) const
Sets a vec3 uniform.
Definition at line 194 of file Shader.cpp.
Referenced by renderRaster().
use()
void Shader::use () const
Binds the shader program for subsequent draw calls.
Definition at line 169 of file Shader.cpp.
References ID, and valid.
Referenced by operator=(), renderRaster(), and renderRay().
Member Data Documentation
ID
unsigned int Shader::ID = 0
OpenGL program object ID.
Definition at line 24 of file Shader.h.
Referenced by operator=(), Shader(), use(), and ~Shader().
valid
bool Shader::valid = false
Whether the shader compiled and linked successfully.
Definition at line 27 of file Shader.h.
Referenced by isValid(), Shader(), and use().
The documentation for this class was generated from the following files:
include/render/Shader.h
src/render/Shader.cpp