OpenGL Ray/Path Tracing: Model Class Reference
Model Class Reference
Loads and stores a 3D model composed of one or more Mesh objects.
#include <model.h>
Public Member Functions
Model (const Model &)=delete
Copying is disabled to avoid duplicating heavy GPU resources.
Model & operator= (const Model &)=delete
Model (Model &&)=default
Move constructor — safe resource transfer.
Model & operator= (Model &&) noexcept=default
Move assignment — safe resource transfer.
Model (const std::string &path)
Constructs a model by loading it from disk.
void Draw () const
Draws all meshes contained in this model.
Public Attributes
std::vector< Mesh > meshes
List of sub-meshes forming this model.
Detailed Description
Loads and stores a 3D model composed of one or more Mesh objects.
This class wraps the model import pipeline using Assimp, converting imported meshes into the local Mesh representation. Each Assimp mesh becomes a separate Mesh instance with its own VBO/EBO/VAO stored on the GPU.
The class is move-only to ensure safe ownership of GPU resources. It follows standard RAII: destruction automatically frees all GPU buffers contained in its Mesh sub-objects.
Definition at line 49 of file model.h.
Constructor & Destructor Documentation
Model() [1/3]
Model::Model (const Model &) delete
Copying is disabled to avoid duplicating heavy GPU resources.
References Model().
Referenced by Model(), Model(), Model(), operator=(), and operator=().
Model() [2/3]
Model::Model (Model &&) default
Move constructor — safe resource transfer.
References Model().
Model() [3/3]
Model::Model (const std::string & path) inline explicit
Constructs a model by loading it from disk.
Parameters
path Path to the model file (OBJ, FBX, etc. supported by Assimp).
The constructor immediately calls loadModel() and populates the meshes vector.
Definition at line 76 of file model.h.
References Model().
Member Function Documentation
Draw()
void Model::Draw () const inline
Draws all meshes contained in this model.
The actual rendering is delegated to each Mesh::Draw() call.
Definition at line 85 of file model.h.
References meshes.
operator=() [1/2]
Model & Model::operator= (const Model &) delete
References Model().
operator=() [2/2]
Model & Model::operator= (Model &&) default noexcept
Move assignment — safe resource transfer.
References Model().
Member Data Documentation
meshes
std::vector<Mesh> Model::meshes
List of sub-meshes forming this model.
Definition at line 52 of file model.h.
Referenced by Draw(), and gather_model_triangles().
The documentation for this class was generated from the following file:
include/scene/model.h