OpenGL Ray/Path Tracing: include/render/cubemap.h File Reference
cubemap.h File Reference
#include <string>
#include "glad/gl.h"
Functions
GLuint createDummyCubeMap ()
Creates a placeholder cube map texture.
GLuint loadCubeMapFromCross (const std::string &path)
Loads a cube map from a cross-layout image file.
Function Documentation
createDummyCubeMap()
GLuint createDummyCubeMap ()
Creates a placeholder cube map texture.
This function generates a minimal valid cube map using solid colors. It is primarily used during initialization when the user has not yet selected an environment map, ensuring that shaders relying on a cube map can still bind a valid texture.
Returns
OpenGL texture handle for the dummy cube map.
Definition at line 7 of file cubemap.cpp.
loadCubeMapFromCross()
GLuint loadCubeMapFromCross (const std::string & path)
Loads a cube map from a cross-layout image file.
The function expects a single image containing all six cube map faces arranged in a cross pattern (typical for HDR environment maps). The loader slices the source image into individual faces and uploads them into an OpenGL cube map texture.
Parameters
path Filesystem path to the cross-layout image.
Returns
OpenGL texture handle for the uploaded cube map. Returns 0 if loading fails.
Definition at line 35 of file cubemap.cpp.
References stbi_image_free(), stbi_load(), and stbi_set_flip_vertically_on_load().