OpenGL Ray/Path Tracing: io Namespace Reference
io Namespace Reference
Input system: keyboard/mouse handling, per-frame user state, and camera interaction.
Classes
struct InputState
Stores all per-frame and edge-triggered input information.
Functions
void init (InputState &)
Optional initialization step for future extension.
bool update (InputState &s, GLFWwindow *win)
Processes GLFW input and updates the InputState for this frame.
void attach_callbacks (GLFWwindow *window)
Attaches GLFW mouse and scroll callbacks used for camera control.
static bool keyDown (GLFWwindow *w, const int key)
static void mouse_cb (GLFWwindow *w, const double xPos, const double yPos)
static void scroll_cb (GLFWwindow *w, double, const double yOff)
Detailed Description
Input system: keyboard/mouse handling, per-frame user state, and camera interaction.
Function Documentation
attach_callbacks()
void io::attach_callbacks (GLFWwindow * window)
Attaches GLFW mouse and scroll callbacks used for camera control.
These callbacks only register raw input data (mouse deltas and scroll offsets). Interpretation—such as updating camera orientation or changing FOV—is handled later inside io::update().
Parameters
window GLFW window to attach event callbacks to.
Definition at line 203 of file input.cpp.
References mouse_cb(), and scroll_cb().
init()
void io::init (InputState &) inline
Optional initialization step for future extension.
Currently a placeholder, but kept to maintain symmetry with other modules of the engine.
Definition at line 80 of file input.h.
keyDown()
bool io::keyDown (GLFWwindow * w, const int key) inline static
Definition at line 9 of file input.cpp.
Referenced by update().
mouse_cb()
void io::mouse_cb (GLFWwindow * w, const double xPos, const double yPos) static
Definition at line 161 of file input.cpp.
References AppState::input, and io::InputState::lastX.
Referenced by attach_callbacks().
scroll_cb()
void io::scroll_cb (GLFWwindow * w, double , const double yOff) static
Definition at line 190 of file input.cpp.
References AppState::camera, and Camera::Fov.
Referenced by attach_callbacks().
update()
bool io::update (InputState & s, GLFWwindow * win)
Processes GLFW input and updates the InputState for this frame.
This function handles:
key edge detection (toggles, mode switches, SPP changes)
ESC quit request
FOV changes from scroll input
pointer lock transitions
The main loop uses the returned boolean to determine whether the accumulation buffer must be reset (e.g., camera moved, SPP changed).
Parameters
s Reference to the input state that will be updated.
win Pointer to the GLFW window used for polling.
Returns
True if any input event requires re-render accumulation reset.
Definition at line 16 of file input.cpp.
References io::InputState::cameraChangedThisFrame, io::InputState::changedSPP, io::InputState::cycledSPP, io::InputState::exposure, keyDown(), io::InputState::prevF2, io::InputState::prevF3, io::InputState::prevF5, io::InputState::prevF6, io::InputState::prevP, io::InputState::prevR, io::InputState::quitRequested, io::InputState::resetAccum, io::InputState::sppPerFrame, io::InputState::toggledBVH, io::InputState::toggledMotionDebug, io::InputState::toggledPointerMode, and io::InputState::toggledRayMode.