OpenGL Ray/Path Tracing: shader_detail Namespace Reference
shader_detail Namespace Reference
Internal shader utilities: GLSL preprocessing, include expansion, and file helpers.
Functions
std::string getDirectory (const std::string &path)
std::string preprocessShaderSource (const std::string &source, const std::string &baseDir, int depth=0)
Detailed Description
Internal shader utilities: GLSL preprocessing, include expansion, and file helpers.
Function Documentation
getDirectory()
std::string shader_detail::getDirectory (const std::string & path)
Definition at line 12 of file Shader.cpp.
Referenced by preprocessShaderSource(), and Shader::Shader().
preprocessShaderSource()
std::string shader_detail::preprocessShaderSource (const std::string & source, const std::string & baseDir, int depth = 0)
Definition at line 22 of file Shader.cpp.
References getDirectory(), and preprocessShaderSource().
Referenced by preprocessShaderSource(), and Shader::Shader().