OpenGL Ray/Path Tracing: ui Namespace Reference
ui Namespace Reference
ImGui user interface layer: control panels, pickers, HUD elements, and debug console.
Classes
struct BvhModelPickerState
Stores UI state for selecting BVH models.
struct EnvMapPickerState
Stores UI state for selecting environment maps.
struct DebugConsole
Functions
void Init (GLFWwindow *window)
Initializes the UI system (Dear ImGui).
void Shutdown ()
Shuts down all UI-related resources.
void BeginFrame ()
Begins a new UI frame.
void EndFrame ()
Finalizes the UI frame and renders the UI draw data.
void Draw (RenderParams &params, const rt::FrameState &frame, const io::InputState &input, bool &rayMode, bool &useBVH, bool &showMotion, BvhModelPickerState &bvhPicker, EnvMapPickerState &envPicker)
Draws the application's control panel.
void Log (const char *fmt,...)
Appends a message to the UI log window.
static void DrawKeybindLegend ()
static void DrawMainControls (RenderParams &params, const rt::FrameState &frame, const io::InputState &input, bool &rayMode, bool &useBVH, bool &showMotion)
Variables
static DebugConsole gConsole
static bool gShowDebugConsole = false
static std::vector< std::string > gModelFiles
static bool gModelScanDone = false
static std::string gModelDir = "../models"
static std::vector< std::string > gEnvFiles
static bool gEnvScanDone = false
static std::string gEnvDir = "../cubemaps"
Detailed Description
ImGui user interface layer: control panels, pickers, HUD elements, and debug console.
Function Documentation
BeginFrame()
void ui::BeginFrame ()
Begins a new UI frame.
Called at the start of each frame, before rendering the main scene. Initializes ImGui's internal state for that frame.
Definition at line 178 of file gui.cpp.
Draw()
void ui::Draw (RenderParams & params, const rt::FrameState & frame, const io::InputState & input, bool & rayMode, bool & useBVH, bool & showMotion, BvhModelPickerState & bvhPicker, EnvMapPickerState & envPicker)
Draws the application's control panel.
This UI exposes:
Material and lighting parameters (RenderParams)
Toggling between raster and ray tracing modes
BVH usage toggle and BVH model picker
Motion-vector visualization options
Debug information from InputState and FrameState
Parameters
params Render parameters to modify.
frame Current frame state for debug visualization.
input Input state (read-only).
rayMode Toggle between raster and ray/path tracing.
useBVH Toggle BVH acceleration structure.
showMotion Toggle motion-vector debug mode.
bvhPicker UI state for BVH model selection.
envPicker UI state for environment map selection.
Definition at line 690 of file gui.cpp.
References ui::BvhModelPickerState::currentPath, ui::EnvMapPickerState::currentPath, DrawKeybindLegend(), DrawMainControls(), gConsole, gEnvDir, gEnvFiles, gEnvScanDone, gModelDir, gModelFiles, gModelScanDone, gShowDebugConsole, Log(), ui::BvhModelPickerState::reloadRequested, ui::EnvMapPickerState::reloadRequested, util::resolve_dir(), io::InputState::sceneInputEnabled, ui::BvhModelPickerState::selectedIndex, and ui::EnvMapPickerState::selectedIndex.
DrawKeybindLegend()
void ui::DrawKeybindLegend () static
Definition at line 631 of file gui.cpp.
Referenced by Draw().
DrawMainControls()
void ui::DrawMainControls (RenderParams & params, const rt::FrameState & frame, const io::InputState & input, bool & rayMode, bool & useBVH, bool & showMotion) static
Definition at line 187 of file gui.cpp.
References RenderParams::aoBias, RenderParams::aoMin, RenderParams::aoRadius, RenderParams::aoSamples, RenderParams::enableAO, RenderParams::enableEnvMap, RenderParams::enableGI, RenderParams::enableJitter, RenderParams::enableSVGF, RenderParams::enableTAA, RenderParams::envMapIntensity, RenderParams::exposure, RenderParams::giScaleAnalytic, RenderParams::giScaleBVH, gShowDebugConsole, RenderParams::jitterMovingScale, RenderParams::jitterStillScale, Log(), RenderParams::matAlbedoColor, RenderParams::matAlbedoGloss, RenderParams::matAlbedoSpecStrength, RenderParams::matGlassColor, RenderParams::matGlassDistortion, RenderParams::matGlassEnabled, RenderParams::matGlassIOR, RenderParams::matMirrorColor, RenderParams::matMirrorEnabled, RenderParams::matMirrorGloss, RenderParams::pointLightColor, RenderParams::pointLightEnabled, RenderParams::pointLightIntensity, RenderParams::pointLightOrbitEnabled, RenderParams::pointLightOrbitRadius, RenderParams::pointLightOrbitSpeed, RenderParams::pointLightPitch, RenderParams::pointLightPos, RenderParams::pointLightYaw, RenderParams::skyColor, RenderParams::skyEnabled, RenderParams::skyIntensity, RenderParams::skyPitch, RenderParams::skyYaw, RenderParams::sppPerFrame, RenderParams::sunColor, RenderParams::sunEnabled, RenderParams::sunIntensity, RenderParams::sunPitch, RenderParams::sunYaw, RenderParams::svgfKColor, RenderParams::svgfKColorMotion, RenderParams::svgfKVar, RenderParams::svgfKVarMotion, RenderParams::svgfMotionEPS, RenderParams::svgfStrength, RenderParams::svgfVarEPS, RenderParams::svgfVarMax, RenderParams::taaHardMovingThresh, RenderParams::taaHistoryAvgWeight, RenderParams::taaHistoryBoxSize, RenderParams::taaHistoryMaxWeight, RenderParams::taaHistoryMinWeight, and RenderParams::taaStillThresh.
Referenced by Draw().
EndFrame()
void ui::EndFrame ()
Finalizes the UI frame and renders the UI draw data.
Called after the main scene has been rendered to the back buffer. Issues all ImGui draw calls.
Definition at line 903 of file gui.cpp.
Init()
void ui::Init (GLFWwindow * window)
Initializes the UI system (Dear ImGui).
Must be called exactly once after the OpenGL context and GLFW window have been created. Sets up ImGui backend bindings for GLFW and OpenGL.
Parameters
window Pointer to the GLFW window used for input and rendering.
Definition at line 154 of file gui.cpp.
Log()
void ui::Log (const char * fmt, ...)
Appends a message to the UI log window.
Supports printf-style formatting.
Parameters
fmt Format string.
... Format arguments.
Definition at line 135 of file gui.cpp.
References gConsole.
Referenced by Draw(), and DrawMainControls().
Shutdown()
void ui::Shutdown ()
Shuts down all UI-related resources.
Called once during application shutdown. Frees ImGui contexts and backend bindings.
Definition at line 172 of file gui.cpp.
Variable Documentation
gConsole
DebugConsole ui::gConsole static
Definition at line 109 of file gui.cpp.
Referenced by Draw(), and Log().
gEnvDir
std::string ui::gEnvDir = "../cubemaps" static
Definition at line 120 of file gui.cpp.
Referenced by Draw().
gEnvFiles
std::vector<std::string> ui::gEnvFiles static
Definition at line 118 of file gui.cpp.
Referenced by Draw().
gEnvScanDone
bool ui::gEnvScanDone = false static
Definition at line 119 of file gui.cpp.
Referenced by Draw().
gModelDir
std::string ui::gModelDir = "../models" static
Definition at line 115 of file gui.cpp.
Referenced by Draw().
gModelFiles
std::vector<std::string> ui::gModelFiles static
Definition at line 113 of file gui.cpp.
Referenced by Draw().
gModelScanDone
bool ui::gModelScanDone = false static
Definition at line 114 of file gui.cpp.
Referenced by Draw().
gShowDebugConsole
bool ui::gShowDebugConsole = false static
Definition at line 110 of file gui.cpp.
Referenced by Draw(), and DrawMainControls().