OpenGL Ray/Path Tracing: src/render/render.cpp File Reference
render.cpp File Reference
#include "render/render.h"
#include <glad/gl.h>
#include <glm/gtc/matrix_transform.hpp>
#include "glm/gtc/type_ptr.hpp"
Functions
glm::vec3 computePointLightWorldPos (const RenderParams &params)
static glm::vec3 dirFromYawPitch (float yawDeg, float pitchDeg)
void renderRay (AppState &app, const int fbw, const int fbh, const bool cameraMoved, const glm::mat4 &currView, const glm::mat4 &currProj)
Executes the ray/path tracing rendering path.
void renderRaster (const AppState &app, const int fbw, const int fbh, const glm::mat4 &currView, const glm::mat4 &currProj)
Executes the rasterization rendering path for debugging or comparison.
Function Documentation
computePointLightWorldPos()
glm::vec3 computePointLightWorldPos (const RenderParams & params)
Definition at line 8 of file render.cpp.
References RenderParams::pointLightOrbitEnabled, RenderParams::pointLightOrbitRadius, RenderParams::pointLightPitch, RenderParams::pointLightPos, and RenderParams::pointLightYaw.
Referenced by renderRaster(), and renderRay().
dirFromYawPitch()
glm::vec3 dirFromYawPitch (float yawDeg, float pitchDeg) static
Definition at line 35 of file render.cpp.
Referenced by renderRay().
renderRaster()
void renderRaster (const AppState & app, int fbw, int fbh, const glm::mat4 & currView, const glm::mat4 & currProj)
Executes the rasterization rendering path for debugging or comparison.
This function renders the scene using the standard raster pipeline. It is primarily used as a reference image for comparison with the ray tracing output, and for rendering BVH debug geometry when enabled.
Parameters
app Read-only application state containing models and shaders.
fbw Framebuffer width.
fbh Framebuffer height.
currView Current view matrix.
currProj Current projection matrix.
Definition at line 249 of file render.cpp.
References AppState::bunny, computePointLightWorldPos(), AppState::ground, AppState::params, RenderParams::pointLightColor, RenderParams::pointLightEnabled, AppState::rasterShader, Shader::setMat4(), Shader::setVec3(), AppState::sphere, and Shader::use().
renderRay()
void renderRay (AppState & app, int fbw, int fbh, bool cameraMoved, const glm::mat4 & currView, const glm::mat4 & currProj)
Executes the ray/path tracing rendering path.
This function drives the full ray tracing pipeline for the current frame. It binds the appropriate accumulation FBO, updates uniforms, dispatches the main ray tracing shader, and handles accumulation reset when needed.
Parameters
app Global application state (accum buffers, shaders, camera, params).
fbw Framebuffer width.
fbh Framebuffer height.
cameraMoved True if the camera moved this frame, forcing accumulation reset.
currView Current view matrix.
currProj Current projection matrix.
Definition at line 55 of file render.cpp.
References AppState::accum, RenderParams::aoBias, RenderParams::aoMin, RenderParams::aoRadius, RenderParams::aoSamples, Camera::AspectRatio, rt::Accum::bindWriteFBO_MRT(), AppState::bvh, AppState::bvhNodeCount, AppState::bvhTriCount, AppState::camera, computePointLightWorldPos(), rt::FrameState::currViewProj, dirFromYawPitch(), RenderParams::enableAO, RenderParams::enableEnvMap, RenderParams::enableGI, RenderParams::enableJitter, RenderParams::enableSVGF, RenderParams::enableTAA, RenderParams::envMapIntensity, AppState::envMapTex, RenderParams::EPS, RenderParams::exposure, Camera::Fov, AppState::frame, rt::Accum::frameIndex, AppState::fsVao, AppState::gBuffer, RenderParams::giScaleAnalytic, RenderParams::giScaleBVH, RenderParams::INF, rt::FrameState::jitter, RenderParams::matAlbedoColor, RenderParams::matAlbedoGloss, RenderParams::matAlbedoSpecStrength, RenderParams::matGlassColor, RenderParams::matGlassDistortion, RenderParams::matGlassEnabled, RenderParams::matGlassIOR, RenderParams::matMirrorColor, RenderParams::matMirrorEnabled, RenderParams::matMirrorGloss, RenderParams::motionScale, rt::Accum::motionTex, BVHHandle::nodeTex, rt::GBuffer::nrmTex, AppState::params, RenderParams::PI, RenderParams::pointLightColor, RenderParams::pointLightEnabled, RenderParams::pointLightIntensity, Camera::Position, rt::GBuffer::posTex, AppState::presentShader, rt::FrameState::prevViewProj, rt::Accum::readTex(), AppState::rtShader, Shader::setFloat(), Shader::setInt(), Shader::setVec2(), AppState::showMotion, RenderParams::skyColor, RenderParams::skyEnabled, RenderParams::skyIntensity, RenderParams::skyPitch, RenderParams::skyYaw, RenderParams::sppPerFrame, RenderParams::sunColor, RenderParams::sunEnabled, RenderParams::sunIntensity, RenderParams::sunPitch, RenderParams::sunYaw, RenderParams::svgfKColor, RenderParams::svgfKColorMotion, RenderParams::svgfKVar, RenderParams::svgfKVarMotion, RenderParams::svgfMotionEPS, RenderParams::svgfStrength, RenderParams::svgfVarEPS, RenderParams::svgfVarMax, rt::Accum::swapAfterFrame(), RenderParams::taaHardMovingThresh, RenderParams::taaHistoryAvgWeight, RenderParams::taaHistoryBoxSize, RenderParams::taaHistoryMaxWeight, RenderParams::taaHistoryMinWeight, RenderParams::taaStillThresh, BVHHandle::triTex, Shader::use(), AppState::useBVH, and rt::Accum::writeTex().