OpenGL Ray/Path Tracing: ui::DebugConsole Struct Reference
ui::DebugConsole Struct Reference
Public Member Functions
DebugConsole ()
void Clear ()
void AddLog (const char *fmt,...) IM_FMTARGS(2)
void Draw (const char *title, bool *pOpen)
Public Attributes
ImGuiTextBuffer Buf
ImGuiTextFilter Filter
ImVector< int > LineOffsets
bool AutoScroll = true
Detailed Description
Definition at line 16 of file gui.cpp.
Constructor & Destructor Documentation
DebugConsole()
ui::DebugConsole::DebugConsole () inline
Definition at line 22 of file gui.cpp.
References Clear().
Member Function Documentation
AddLog()
void ui::DebugConsole::AddLog (const char * fmt, ...) inline
Definition at line 34 of file gui.cpp.
References Buf, and LineOffsets.
Clear()
void ui::DebugConsole::Clear () inline
Definition at line 27 of file gui.cpp.
References Buf, and LineOffsets.
Referenced by DebugConsole(), and Draw().
Draw()
void ui::DebugConsole::Draw (const char * title, bool * pOpen) inline
Definition at line 50 of file gui.cpp.
References AutoScroll, Buf, Clear(), Filter, and LineOffsets.
Member Data Documentation
AutoScroll
bool ui::DebugConsole::AutoScroll = true
Definition at line 20 of file gui.cpp.
Referenced by Draw().
Buf
ImGuiTextBuffer ui::DebugConsole::Buf
Definition at line 17 of file gui.cpp.
Referenced by AddLog(), Clear(), and Draw().
Filter
ImGuiTextFilter ui::DebugConsole::Filter
Definition at line 18 of file gui.cpp.
Referenced by Draw().
LineOffsets
ImVector<int> ui::DebugConsole::LineOffsets
Definition at line 19 of file gui.cpp.
Referenced by AddLog(), Clear(), and Draw().
The documentation for this struct was generated from the following file:
src/ui/gui.cpp